### ISSUE TITLE
Addon is overwriting the global Item table in-game

### ISSUE THREAD

**Issue by Hekili** [ollidiemaus/healthstoneAutoMacro#14]
The `Item` table in WoW is used for loading and validating items for testing purposes.  Your latest version of the addon overwrites the existing global table with a blank table before adding elements, here:

https://github.com/ollidiemaus/healthstoneAutoMacro/blob/main/Core/Item.lua#L1

I would recommend using a different able name or keeping your addon tables within your addon's namespace instead.  Otherwise, this will break all other addons that use the Item table and/or taint the base UI when it looks for those item functions.

**Comment by dubudevs** [comment]
A large number of my addons broke after this update for this reason. Disabling/rolling back fixed it.

**Comment by ollidiemaus** [comment]
Thanks.
Yeah that was my bad I'll fix it.

**Comment by ollidiemaus** [comment]
Okay turns out I just keep using my own namespace might be the best idea.
Don't wanna mess with any other addons.
Thanks for the Feedback anyways :)
