### ISSUE TITLE
Fortitude of the Bear 

### ISSUE THREAD

**Issue by Xorm1** [ollidiemaus/healthstoneAutoMacro#18]
Just a suggestion to add to the list. I know you must be busy, but this would be a great help to all BM hunters. :) This macro is great and has vastly improved my survivability, I am about to go check out your other auto macro now and add it. 

side note making one of these for defensive cool downs would be awesome. thank you from someone that is a reformed clicker!

**Comment by ollidiemaus** [comment]
this is added in 2.5.5
