### ISSUE TITLE
packaged release

### ISSUE THREAD

**Issue by srbrunner** [ollidiemaus/healthstoneAutoMacro#8]
This isn't a bug, but can you provide a packaged release or upload to wag.io?  Basically, when you release a version add a zip'd release along with the source files.

Thanks for your consideration. @

**Comment by cdurth** [comment]
also requesting this.
additional information for release config can be found here: https://wowup.io/guide/get-addons/overview

**Comment by ollidiemaus** [comment]
Yeah i already tried but the webhook is broken and the wago support is not answering since weeks

**Comment by ollidiemaus** [comment]
So for now I provided a package release bu ill work on improving the release workflow to also support wago
